// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6IlDAZrmGXDcdPyrSxZmpb5jEICFN80',
    appId: '1:284750201188:web:bd376743d2445b4cf77a71',
    messagingSenderId: '284750201188',
    projectId: 'stream-sync-78382',
    authDomain: 'stream-sync-78382.firebaseapp.com',
    storageBucket: 'stream-sync-78382.firebasestorage.app',
    measurementId: 'G-QDXHHLKKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HNimADi7L1eJxoYjf3limM4lg68RgdY',
    appId: '1:284750201188:android:2ae901b9d69dadb7f77a71',
    messagingSenderId: '284750201188',
    projectId: 'stream-sync-78382',
    storageBucket: 'stream-sync-78382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaWvqJCstHz8IdZtoyrY64ryZSaflk5CY',
    appId: '1:284750201188:ios:a683a8fda0dfc893f77a71',
    messagingSenderId: '284750201188',
    projectId: 'stream-sync-78382',
    storageBucket: 'stream-sync-78382.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaWvqJCstHz8IdZtoyrY64ryZSaflk5CY',
    appId: '1:284750201188:ios:a683a8fda0dfc893f77a71',
    messagingSenderId: '284750201188',
    projectId: 'stream-sync-78382',
    storageBucket: 'stream-sync-78382.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6IlDAZrmGXDcdPyrSxZmpb5jEICFN80',
    appId: '1:284750201188:web:1ae408bf9516faa5f77a71',
    messagingSenderId: '284750201188',
    projectId: 'stream-sync-78382',
    authDomain: 'stream-sync-78382.firebaseapp.com',
    storageBucket: 'stream-sync-78382.firebasestorage.app',
    measurementId: 'G-C6DYZ2NRG0',
  );
}
